import { act, fireEvent, render, screen, waitFor, within } from '@testing-library/react'
import { MemoryRouter, Route, Routes } from 'react-router-dom'
import { beforeEach, describe, expect, it, vi } from 'vitest'
import Labs, { LabDetailPage } from './Labs'
import { labsApi } from '../services/api'

vi.mock('../services/api', () => ({ labsApi: {
  list: vi.fn(), get: vi.fn(), create: vi.fn(), update: vi.fn(), remove: vi.fn(),
  members: vi.fn(), memberOptions: vi.fn(), addMember: vi.fn(), removeMember: vi.fn(), papers: vi.fn(),
  paperOptions: vi.fn(), addPapers: vi.fn(), removePaper: vi.fn(),
  piOptions: vi.fn(),
} }))

const lab = { id: 'lab_1', name: 'Language Lab', description: 'Language research', createdAt: '2026-10-07' }
const member = { authorId: 'a_1', name: 'Jane Smith', orcid: null }
const paper = { id: 'p_1', title: 'Shared research', authors: ['Jane Smith'], year: 2026, venue: 'ICLR', status: 'read', libraryName: 'Research' }
const page = (items, limit = 25, total = items.length, offset = 0) => ({ items, limit, total, offset })
const mount = (path = '/labs/lab_1') => render(<MemoryRouter initialEntries={[path]}><Routes><Route path="/labs" element={<Labs />} /><Route path="/labs/:id" element={<LabDetailPage />} /></Routes></MemoryRouter>)

beforeEach(() => {
  vi.resetAllMocks()
  labsApi.list.mockResolvedValue(page([lab], 30))
  labsApi.get.mockResolvedValue(lab)
  labsApi.members.mockResolvedValue(page([member], 50))
  labsApi.papers.mockResolvedValue(page([paper]))
  labsApi.memberOptions.mockResolvedValue([{ authorId: 'a_2', name: 'John Smith' }])
  labsApi.addMember.mockResolvedValue({ authorId: 'a_2', name: 'John Smith' })
  labsApi.removeMember.mockResolvedValue(null)
  labsApi.paperOptions.mockResolvedValue(page([{ ...paper, id: 'p_2', title: 'Available paper' }]))
  labsApi.addPapers.mockResolvedValue({ addedCount: 1 })
  labsApi.removePaper.mockResolvedValue(null)
  labsApi.piOptions.mockResolvedValue([member, { authorId: 'a_2', name: 'John Smith', orcid: null }])
})

describe('Labs', () => {
  it('renders directory cards with one list request and only loads details after opening a card', async () => {
    labsApi.list.mockResolvedValue(page([{ ...lab, principalInvestigators: [member, { authorId: 'a_2', name: 'John Smith' }] }], 30))
    mount('/labs')
    const card = await screen.findByRole('link', { name: 'Open Language Lab' })
    expect(card).toHaveAttribute('href', '/labs/lab_1')
    expect(within(card).getByLabelText('Principal investigators')).toHaveTextContent('Jane Smith, John Smith')
    expect(screen.getByText('Language research')).toBeInTheDocument()
    expect(labsApi.list).toHaveBeenCalledTimes(1)
    for (const method of ['get', 'members', 'papers']) expect(labsApi[method]).not.toHaveBeenCalled()
    fireEvent.click(card)
    await screen.findByRole('link', { name: paper.title })
    expect(screen.getByRole('heading', { level: 1, name: lab.name })).toBeInTheDocument()
    expect(screen.getByRole('complementary', { name: 'Lab people' })).toBeInTheDocument()
    expect(screen.queryByRole('list', { name: 'Labs directory' })).not.toBeInTheDocument()
    expect(labsApi.list).toHaveBeenCalledTimes(1)
  })

  it('uses the filtered member page and keeps the header free of placeholder copy', async () => {
    labsApi.get.mockResolvedValue({ ...lab, description: null, principalInvestigators: [member] })
    labsApi.members.mockResolvedValue(page([{ authorId: 'other', name: 'Alex Lee' }], 50))
    mount()
    await screen.findByRole('link', { name: 'Alex Lee' })
    const members = within(screen.getByRole('region', { name: 'Lab members' }))
    expect(members.queryByRole('link', { name: member.name })).not.toBeInTheDocument()
    expect(members.getByRole('heading', { name: 'Members (1)' })).toBeInTheDocument()
    expect(within(screen.getByRole('region', { name: 'Principal investigators' })).getByRole('link', { name: member.name })).toBeInTheDocument()
    expect(labsApi.members).toHaveBeenCalledWith(lab.id, { offset: 0, limit: 50, excludePis: true })
    for (const text of ['Research lab', 'Add a description to introduce', 'Selected research from across your libraries.', 'Removing a paper here only unlinks it from this lab.', 'Members and papers are managed independently.']) {
      expect(screen.queryByText(text, { exact: false })).not.toBeInTheDocument()
    }
    expect(screen.getByRole('button', { name: 'Edit lab' })).toHaveTextContent(/^edit$/)
    expect(screen.getByRole('button', { name: 'Delete lab' })).toHaveTextContent(/^delete$/)
  })

  it('keeps old lab bookmarks working without fetching the directory', async () => {
    mount('/labs?lab=lab_1')
    await screen.findByRole('link', { name: paper.title })
    expect(labsApi.get).toHaveBeenCalledWith('lab_1')
    expect(labsApi.list).not.toHaveBeenCalled()
  })

  it('restores directory search and pagination when returning from a lab', async () => {
    labsApi.list.mockResolvedValue(page([lab], 30, 61, 30))
    mount('/labs?search=Language&offset=30')
    fireEvent.click(await screen.findByRole('link', { name: 'Open Language Lab' }))
    fireEvent.click(await screen.findByRole('link', { name: 'All labs' }))
    await screen.findByRole('link', { name: 'Open Language Lab' })
    expect(screen.getByRole('textbox', { name: 'Search labs' })).toHaveValue('Language')
    expect(labsApi.list).toHaveBeenLastCalledWith({ search: 'Language', limit: 30, offset: 30 })
  })

  it('saves multiple websites and PIs together, retains them on failure, and can clear them', async () => {
    const pis = [member, { authorId: 'a_2', name: 'John Smith', orcid: null }]
    const detailed = { ...lab, websites: ['https://lab.example/', 'https://lab.example/projects'], principalInvestigators: pis }
    labsApi.update.mockRejectedValueOnce(new Error('PI was deleted')).mockResolvedValueOnce(detailed).mockResolvedValueOnce({ ...lab, websites: [], principalInvestigators: [] })
    mount()
    await screen.findByRole('link', { name: paper.title })
    fireEvent.click(screen.getByRole('button', { name: 'Edit lab' }))
    expect(labsApi.piOptions).not.toHaveBeenCalled()
    fireEvent.change(screen.getByLabelText('Website 1'), { target: { value: detailed.websites[0] } })
    fireEvent.click(screen.getByRole('button', { name: 'Add website' }))
    fireEvent.change(screen.getByLabelText('Website 2'), { target: { value: detailed.websites[1] } })
    fireEvent.change(screen.getByLabelText('Search PI authors'), { target: { value: 'Smith' } })
    fireEvent.click(await screen.findByRole('button', { name: 'Select PI Jane Smith' }))
    fireEvent.click(screen.getByRole('button', { name: 'Select PI John Smith' }))
    expect(screen.getByRole('button', { name: 'Select PI Jane Smith' })).toBeDisabled()
    fireEvent.click(screen.getByRole('button', { name: 'Save changes' }))
    expect(await screen.findByRole('alert')).toHaveTextContent('PI was deleted')
    expect(screen.getByLabelText('Website 2')).toHaveValue(detailed.websites[1])
    expect(screen.getByRole('button', { name: 'Remove PI Jane Smith' })).toBeInTheDocument()
    fireEvent.click(screen.getByRole('button', { name: 'Save changes' }))
    const piSection = await screen.findByRole('region', { name: 'Principal investigators' })
    await waitFor(() => expect(within(piSection).getByRole('link', { name: 'John Smith' })).toHaveAttribute('href', '/authors/a_2'))
    expect(labsApi.update).toHaveBeenLastCalledWith(lab.id, { name: lab.name, description: lab.description, websites: detailed.websites, piAuthorIds: ['a_1', 'a_2'] })
    expect(screen.getByRole('link', { name: 'https://lab.example/' })).toHaveAttribute('rel', 'noopener noreferrer')
    fireEvent.click(screen.getByRole('button', { name: 'Edit lab' }))
    fireEvent.click(screen.getByRole('button', { name: 'Remove website 2' }))
    fireEvent.click(screen.getByRole('button', { name: 'Remove website 1' }))
    for (const pi of pis) fireEvent.click(screen.getByRole('button', { name: `Remove PI ${pi.name}` }))
    fireEvent.click(screen.getByRole('button', { name: 'Save changes' }))
    await waitFor(() => expect(labsApi.update).toHaveBeenLastCalledWith(lab.id, { name: lab.name, description: lab.description, websites: [], piAuthorIds: [] }))
    expect(labsApi.papers).toHaveBeenCalledTimes(1)
    await waitFor(() => expect(labsApi.members).toHaveBeenCalledTimes(3))
    expect(labsApi.addMember).not.toHaveBeenCalled()
    expect(labsApi.addPapers).not.toHaveBeenCalled()
  })

  it('loads one bounded resource per section and links papers and authors', async () => {
    mount()
    expect(await screen.findByRole('link', { name: 'Shared research' })).toHaveAttribute('href', '/library/paper/p_1')
    expect(screen.getByRole('link', { name: 'Jane Smith' })).toHaveAttribute('href', '/authors/a_1')
    expect(screen.getAllByRole('columnheader').map(header => header.textContent)).toEqual(['Title', 'Year', 'Actions'])
    for (const method of ['get', 'members', 'papers']) expect(labsApi[method]).toHaveBeenCalledTimes(1)
    expect(labsApi.memberOptions).not.toHaveBeenCalled()
  })

  it('creates a lab from the empty state and opens it', async () => {
    labsApi.list.mockResolvedValue(page([], 30))
    labsApi.create.mockResolvedValue(lab)
    mount('/labs')
    expect(await screen.findByText('No labs yet. Create your first lab to get started.')).toBeInTheDocument()
    fireEvent.click(screen.getByRole('button', { name: 'Create lab' }))
    fireEvent.change(screen.getByLabelText('Lab name'), { target: { value: ' Language Lab ' } })
    fireEvent.click(screen.getAllByRole('button', { name: 'Create lab' }).at(-1))
    await screen.findByRole('heading', { name: lab.name })
    expect(labsApi.create).toHaveBeenCalledWith({ name: 'Language Lab', description: null, websites: [], piAuthorIds: [] })
  })

  it('debounces paper search and refreshes only the paper section', async () => {
    mount()
    await screen.findByRole('link', { name: paper.title })
    const search = screen.getByRole('textbox', { name: 'Search lab papers' })
    fireEvent.change(search, { target: { value: 'Sh' } })
    fireEvent.change(search, { target: { value: 'Shared' } })
    await waitFor(() => expect(labsApi.papers).toHaveBeenCalledTimes(2))
    expect(labsApi.papers).toHaveBeenLastCalledWith('lab_1', { search: 'Shared', offset: 0, limit: 25 })
    expect(labsApi.members).toHaveBeenCalledTimes(1)
    expect(labsApi.list).not.toHaveBeenCalled()
    expect(labsApi.get).toHaveBeenCalledTimes(1)
  })

  it('shows member errors, allows retry, and refreshes only affected sections after adding', async () => {
    labsApi.addMember.mockRejectedValueOnce(new Error('Could not add author'))
    mount()
    await screen.findByRole('button', { name: 'Add members' })
    fireEvent.click(screen.getByRole('button', { name: 'Add members' }))
    expect(labsApi.memberOptions).not.toHaveBeenCalled()
    fireEvent.change(screen.getByLabelText('Search authors'), { target: { value: 'John' } })
    fireEvent.click(await screen.findByRole('button', { name: 'Add John Smith' }))
    expect(await screen.findByRole('alert')).toHaveTextContent('Could not add author')
    fireEvent.click(screen.getByRole('button', { name: 'Add John Smith' }))
    await screen.findByText('John Smith added as a member.')
    const checkbox = await screen.findByRole('checkbox', { name: 'Select Available paper' })
    expect(checkbox).not.toBeChecked()
    expect(labsApi.addPapers).not.toHaveBeenCalled()
    expect(labsApi.papers).toHaveBeenCalledTimes(1)
    await waitFor(() => expect(labsApi.members).toHaveBeenCalledTimes(2))
    expect(labsApi.paperOptions).toHaveBeenCalledWith('lab_1', { search: '', author_id: 'a_2', offset: 0, limit: 25 })
    fireEvent.click(checkbox)
    fireEvent.click(screen.getByRole('button', { name: 'Add selected papers (1)' }))
    await waitFor(() => expect(labsApi.papers).toHaveBeenCalledTimes(2))
    expect(labsApi.addPapers).toHaveBeenCalledWith('lab_1', ['p_2'], 'a_2')
    expect(labsApi.get).toHaveBeenCalledTimes(1)
    expect(labsApi.list).not.toHaveBeenCalled()
  })

  it('keeps the paper page after member removal and resets only after unlinking a paper', async () => {
    labsApi.papers.mockResolvedValueOnce(page([paper], 25, 26)).mockResolvedValueOnce(page([paper], 25, 26, 25)).mockResolvedValue(page([], 25))
    mount()
    await screen.findByRole('link', { name: paper.title })
    fireEvent.click(within(screen.getByRole('navigation', { name: 'Papers pagination' })).getByRole('button', { name: 'Next' }))
    await waitFor(() => expect(labsApi.papers).toHaveBeenLastCalledWith('lab_1', { search: '', offset: 25, limit: 25 }))
    await screen.findByText('26–26 of 26')
    fireEvent.click(screen.getByRole('button', { name: 'Remove Jane Smith' }))
    await waitFor(() => expect(labsApi.members).toHaveBeenCalledTimes(2))
    expect(labsApi.papers).toHaveBeenCalledTimes(2)
    expect(screen.getByText('26–26 of 26')).toBeInTheDocument()
    fireEvent.click(screen.getByRole('button', { name: `Remove paper ${paper.title}` }))
    await waitFor(() => expect(labsApi.papers).toHaveBeenLastCalledWith('lab_1', { search: '', offset: 0, limit: 25 }))
    expect(labsApi.removeMember).toHaveBeenCalledWith('lab_1', 'a_1')
    expect(labsApi.removePaper).toHaveBeenCalledWith('lab_1', 'p_1')
  })

  it('keeps edit form values on error and updates metadata without reloading papers', async () => {
    labsApi.update.mockRejectedValueOnce(new Error('Save failed')).mockResolvedValue({ ...lab, name: 'Renamed lab', description: null })
    mount()
    await screen.findByRole('link', { name: paper.title })
    fireEvent.click(screen.getByRole('button', { name: 'Edit lab' }))
    fireEvent.change(screen.getByLabelText('Lab name'), { target: { value: 'Renamed lab' } })
    fireEvent.change(screen.getByLabelText('Description (optional)'), { target: { value: '' } })
    fireEvent.click(screen.getByRole('button', { name: 'Save changes' }))
    expect(await screen.findByRole('alert')).toHaveTextContent('Save failed')
    expect(screen.getByLabelText('Lab name')).toHaveValue('Renamed lab')
    fireEvent.click(screen.getByRole('button', { name: 'Save changes' }))
    await screen.findByRole('heading', { name: 'Renamed lab' })
    expect(labsApi.update).toHaveBeenLastCalledWith('lab_1', { name: 'Renamed lab', description: null, websites: [], piAuthorIds: [] })
    expect(labsApi.papers).toHaveBeenCalledTimes(1)
  })

  it('ignores late responses from a previously selected lab', async () => {
    let resolveOld
    labsApi.list.mockResolvedValue(page([lab, { ...lab, id: 'lab_2', name: 'Vision Lab' }], 30))
    labsApi.papers.mockImplementation(id => id === 'lab_1' ? new Promise(resolve => { resolveOld = resolve }) : Promise.resolve(page([{ ...paper, id: 'p_2', title: 'Vision paper' }])))
    labsApi.get.mockImplementation(id => Promise.resolve(id === 'lab_1' ? lab : { ...lab, id, name: 'Vision Lab' }))
    mount()
    await waitFor(() => expect(labsApi.papers).toHaveBeenCalled())
    fireEvent.click(await screen.findByRole('link', { name: 'All labs' }))
    fireEvent.click(await screen.findByRole('link', { name: 'Open Vision Lab' }))
    await screen.findByRole('link', { name: 'Vision paper' })
    await act(async () => resolveOld(page([paper])))
    expect(screen.queryByRole('link', { name: paper.title })).not.toBeInTheDocument()
  })

  it('retries a failed section and confirms deletion before removing a lab', async () => {
    labsApi.papers.mockRejectedValueOnce(new Error('Paper load failed')).mockResolvedValue(page([paper]))
    labsApi.remove.mockResolvedValue(null)
    mount()
    expect(await screen.findByRole('alert')).toHaveTextContent('Paper load failed')
    fireEvent.click(screen.getByRole('button', { name: 'Retry' }))
    await screen.findByRole('link', { name: paper.title })
    fireEvent.click(screen.getByRole('button', { name: 'Delete lab' }))
    expect(labsApi.remove).not.toHaveBeenCalled()
    expect(screen.getByText(/Author profiles and papers will be kept/)).toBeInTheDocument()
    await act(async () => fireEvent.click(screen.getByRole('button', { name: 'Confirm delete' })))
    await screen.findByRole('heading', { name: 'Labs', exact: true })
    expect(labsApi.remove).toHaveBeenCalledWith('lab_1')
  })

  it('adds an author without any papers when optional selection is skipped', async () => {
    mount()
    fireEvent.click(await screen.findByRole('button', { name: 'Add members' }))
    fireEvent.change(screen.getByLabelText('Search authors'), { target: { value: 'John' } })
    fireEvent.click(await screen.findByRole('button', { name: 'Add John Smith' }))
    fireEvent.click(await screen.findByRole('button', { name: 'Done without adding papers' }))
    expect(labsApi.addMember).toHaveBeenCalledWith('lab_1', 'a_2')
    expect(labsApi.addPapers).not.toHaveBeenCalled()
    expect(labsApi.papers).toHaveBeenCalledTimes(1)
  })

  it('adds papers without members, retains selection across pages/search, and retries failed saves', async () => {
    labsApi.members.mockResolvedValue(page([], 50))
    labsApi.paperOptions.mockImplementation((id, { offset, search }) => Promise.resolve(search
      ? page([{ ...paper, id: 'p_3', title: 'Another available paper' }])
      : page([{ ...paper, id: offset ? 'p_3' : 'p_2', title: offset ? 'Another available paper' : 'Available paper' }], 25, 26, offset)))
    labsApi.addPapers.mockRejectedValueOnce(new Error('Save selection failed')).mockResolvedValue({ addedCount: 2 })
    mount()
    fireEvent.click(await screen.findByRole('button', { name: 'Add papers' }))
    const first = await screen.findByRole('checkbox', { name: 'Select Available paper' })
    expect(first).not.toBeChecked()
    fireEvent.click(first)
    fireEvent.click(within(screen.getByRole('navigation', { name: 'Available papers pagination' })).getByRole('button', { name: 'Next' }))
    fireEvent.click(await screen.findByRole('checkbox', { name: 'Select Another available paper' }))
    fireEvent.change(screen.getByRole('textbox', { name: 'Search papers to add' }), { target: { value: 'Another' } })
    await waitFor(() => expect(labsApi.paperOptions).toHaveBeenLastCalledWith('lab_1', { search: 'Another', author_id: undefined, offset: 0, limit: 25 }))
    expect(await screen.findByRole('checkbox', { name: 'Select Another available paper' })).toBeChecked()
    fireEvent.click(screen.getByRole('button', { name: 'Add selected papers (2)' }))
    expect(await screen.findByRole('alert')).toHaveTextContent('Save selection failed')
    expect(screen.getByRole('button', { name: 'Add selected papers (2)' })).toBeEnabled()
    fireEvent.click(screen.getByRole('button', { name: 'Add selected papers (2)' }))
    await waitFor(() => expect(labsApi.papers).toHaveBeenCalledTimes(2))
    expect(labsApi.addPapers).toHaveBeenLastCalledWith('lab_1', ['p_2', 'p_3'], null)
    expect(labsApi.addMember).not.toHaveBeenCalled()
    expect(labsApi.members).toHaveBeenCalledTimes(1)
  })

  it('offers paper selection for an existing member without adding the member again', async () => {
    mount()
    fireEvent.click(await screen.findByRole('button', { name: 'Choose papers by Jane Smith' }))
    await screen.findByRole('checkbox', { name: 'Select Available paper' })
    expect(labsApi.paperOptions).toHaveBeenCalledWith('lab_1', { search: '', author_id: 'a_1', offset: 0, limit: 25 })
    expect(labsApi.addMember).not.toHaveBeenCalled()
    fireEvent.click(screen.getByRole('button', { name: 'Cancel' }))
    expect(labsApi.addPapers).not.toHaveBeenCalled()
  })
})
